/**
 * Tiger Content Workflow — Task API Service  (Phase 4)
 *
 * Currently using mock data. To connect to Google Apps Script:
 *   GET  ?action=getTasks
 *   POST ?action=updateTask  { id, field, value }
 */

import type { Task, FilterState } from '../types';

// ─── Mock Data — 44 tasks ──────────────────────────────────────────────────

const MOCK_TASKS: Task[] = [

  // ════════════════════════════════════════════════════════════════════════
  // EXISTING TASKS (updated with Phase-4 risk fields)
  // ════════════════════════════════════════════════════════════════════════

  // ── tigersourcingchina.com ──────────────────────────────────────────────
  {
    id: 'TSC-001', website: 'tigersourcingchina.com', contentType: '短视频',
    title: '工厂直采省30%成本——真实案例分享',
    status: '04_小M待剪辑', priority: 'A', isOverdue: true, needsVeraReview: false, assignedTo: '小M',
    videoType: '短视频', editLevel: 'A精剪', materialId: 'MAT-TSC-001',
    materialLink: 'https://drive.google.com/mock/mat-tsc-001',
    scriptLink: 'https://docs.google.com/mock/script-tsc-001',
    coverRequirements: '工厂背景，显示"节省30%"数字', subtitleLanguage: '中文+俄文',
    mDeadline: '2026-05-10', returnNotes: '第一版节奏太慢，前5秒需要更有冲击力',
    riskLevel: '中', aiRiskScore: 42, riskLabels: ['品牌风险'],
    aiDecision: 'vera_required', aiDecisionReason: '有返工意见，需人工确认修改方向',
    nextAssignee: '小S', nextAction: '成片提交后进入小S待终审',
    notes: ['2026-05-08 小S: 脚本已终审通过', '2026-05-09 小M: 素材已收到，开始剪辑'],
    opLog: [
      { time: '2026-05-01 09:00', action: 'AI生成脚本', operator: '龙虾' },
      { time: '2026-05-08 14:30', action: '小S审核通过脚本', operator: '小S' },
      { time: '2026-05-09 10:00', action: '小M开始剪辑', operator: '小M' },
    ],
    createdAt: '2026-05-01', updatedAt: '2026-05-09',
  },
  {
    id: 'TSC-002', website: 'tigersourcingchina.com', contentType: 'SEO文章',
    title: '如何找到可信赖的中国供应商（完整指南）',
    status: '02_小S待审核', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    keywords: '中国供应商, 找货源, sourcing china', keywordSource: 'Ahrefs', skill: 'SEO长文',
    aiOutputLink: 'https://docs.google.com/mock/ai-tsc-002',
    cta: '立即获取采购报价', crmTags: 'sourcing_lead, top_funnel', sDeadline: '2026-05-18',
    riskLevel: '低', aiRiskScore: 18, autoApproved: false,
    approvalRulesHit: ['无价格信息', '无时效承诺'],
    aiDecision: 'auto_approve', aiDecisionReason: '普通SEO文章，无高风险内容',
    nextAssignee: '小C', nextAction: '审核通过后交小C确认URL',
    opLog: [{ time: '2026-05-12 09:00', action: 'AI生成初稿', operator: '龙虾' }],
    createdAt: '2026-05-05', updatedAt: '2026-05-12',
  },
  {
    id: 'TSC-003', website: 'tigersourcingchina.com', contentType: 'Landing Page',
    title: '义乌采购代理服务——落地页',
    status: '03_小C待确认URL', priority: 'A', isOverdue: false, needsVeraReview: false, assignedTo: '小C',
    targetUrl: '/yiwu-sourcing-agent', urlStatus: '待创建', needsNewPage: true,
    lpBrief: '主打义乌一件代发，含询价表单，WhatsApp入口',
    formStatus: '表单待配置', sitemapStatus: '待更新', gscStatus: '待提交', cDeadline: '2026-05-20',
    riskLevel: '中', aiRiskScore: 35, riskLabels: ['页面链接风险'],
    aiDecision: 'vera_required', aiDecisionReason: 'Landing Page上线前必须Vera确认',
    nextAssignee: '小M', nextAction: '页面上线后通知小M添加视频',
    opLog: [{ time: '2026-05-13 10:00', action: '小C开始建页面', operator: '小C' }],
    createdAt: '2026-05-06', updatedAt: '2026-05-13',
  },
  {
    id: 'TSC-004', website: 'tigersourcingchina.com', contentType: '长视频',
    title: 'Tiger采购全流程解析（20分钟完整版）',
    status: '06_Vera待审核', priority: 'A', isOverdue: false, needsVeraReview: true, assignedTo: 'Vera',
    videoType: '长视频', editLevel: 'A精剪',
    finalVideoLink: 'https://drive.google.com/mock/final-tsc-004',
    riskType: 'A类长视频 / 含价格信息',
    reviewLink: 'https://drive.google.com/mock/final-tsc-004', mDeadline: '2026-05-16',
    riskLevel: '高', aiRiskScore: 85, riskLabels: ['A类长视频', '价格风险'],
    aiDecision: 'vera_required', aiDecisionReason: 'A类长视频且含价格信息，必须人工审核',
    approvalRulesHit: [],
    nextAssignee: '小S', nextAction: 'Vera审核通过后发布',
    opLog: [
      { time: '2026-04-28 09:00', action: '任务创建', operator: '小S' },
      { time: '2026-05-14 16:00', action: '小M提交成片', operator: '小M' },
      { time: '2026-05-14 16:05', action: 'AI风险判断：高风险，转Vera', operator: 'AI系统' },
    ],
    createdAt: '2026-04-28', updatedAt: '2026-05-14',
  },

  // ── tigerlogisticschina.com ─────────────────────────────────────────────
  {
    id: 'TLC-001', website: 'tigerlogisticschina.com', contentType: '短视频',
    title: '中俄货运30天必达——Tiger物流承诺',
    status: '01_AI待生成', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '龙虾',
    keywords: '中俄物流, 中国到俄罗斯运货', skill: '短视频脚本', videoType: '短视频', editLevel: 'B标准',
    sDeadline: '2026-05-22',
    riskLevel: '中', aiRiskScore: 62, riskLabels: ['时效风险'],
    aiDecision: 'vera_required', aiDecisionReason: '标题含"30天"时效承诺，生成后需人工复查',
    nextAssignee: '小S', nextAction: 'AI生成脚本后交小S审核',
    opLog: [{ time: '2026-05-13 11:00', action: '小S确认关键词，下发AI生成', operator: '小S' }],
    createdAt: '2026-05-10', updatedAt: '2026-05-13',
  },
  {
    id: 'TLC-002', website: 'tigerlogisticschina.com', contentType: 'SEO文章',
    title: '中国到俄罗斯物流最优方案2026年最新',
    status: '05_小S待终审', priority: 'A', isOverdue: true, needsVeraReview: false, assignedTo: '小S',
    keywords: '中俄物流方案, 中俄货运价格', keywordSource: 'SEMrush', skill: 'SEO长文',
    aiOutputLink: 'https://docs.google.com/mock/ai-tlc-002',
    cta: '获取最新运价', crmTags: 'logistics_lead, russia_market', sDeadline: '2026-05-12',
    riskLevel: '中', aiRiskScore: 58, riskLabels: ['价格风险'],
    aiDecision: 'vera_required', aiDecisionReason: '含运价信息，终审时需人工确认价格准确性',
    nextAssignee: '小C', nextAction: '终审通过后小C确认URL并发布',
    opLog: [
      { time: '2026-05-03 09:00', action: 'AI生成初稿', operator: '龙虾' },
      { time: '2026-05-11 15:00', action: '小S初审通过，发回修改', operator: '小S' },
    ],
    createdAt: '2026-05-03', updatedAt: '2026-05-13',
  },
  {
    id: 'TLC-003', website: 'tigerlogisticschina.com', contentType: '发布文案',
    title: '双十一促销——中俄物流限时优惠发布文案',
    status: '07_待发布', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    targetUrl: '/promotions/1111-2026',
    utmLink: 'https://tigerlogisticschina.com/promotions/1111-2026?utm_source=wechat&utm_medium=social',
    cta: '立即锁定优惠价', crmTags: 'promo_1111, china_russia', sDeadline: '2026-05-15',
    riskLevel: '低', aiRiskScore: 10, autoApproved: true,
    approvalRulesHit: ['普通促销文案', '无时效承诺', '无清关内容', 'CTA已配置', 'UTM已配置'],
    aiDecision: 'auto_approve', aiDecisionReason: '普通促销文案，全部放行条件已满足',
    autoApprovalTime: '2026-05-14 18:00',
    nextAssignee: 'Vera', nextAction: '按计划时间发布至微信+小红书',
    opLog: [
      { time: '2026-05-13 10:00', action: 'AI生成文案', operator: '龙虾' },
      { time: '2026-05-13 14:00', action: 'AI风险评估：低风险', operator: 'AI系统' },
      { time: '2026-05-14 18:00', action: 'AI自动放行，进入发布队列', operator: 'AI系统' },
      { time: '2026-05-14 19:00', action: 'Vera审核通过', operator: 'Vera' },
    ],
    createdAt: '2026-05-08', updatedAt: '2026-05-14',
  },
  {
    id: 'TLC-004', website: 'tigerlogisticschina.com', contentType: 'URL检查',
    title: '物流运费计算器页面——URL与表单检查',
    status: '03_小C待确认URL', priority: 'C', isOverdue: false, needsVeraReview: false, assignedTo: '小C',
    targetUrl: '/freight-calculator', urlStatus: '已存在，需检查', formStatus: '表单待测试',
    sitemapStatus: '已收录', gscStatus: '已索引', cDeadline: '2026-05-19',
    riskLevel: '低', aiRiskScore: 8, aiDecision: 'auto_approve',
    nextAssignee: '小S', nextAction: '检查完成后更新文案',
    createdAt: '2026-05-09', updatedAt: '2026-05-12',
  },

  // ── tiger-logistics.ru ──────────────────────────────────────────────────
  {
    id: 'TLR-001', website: 'tiger-logistics.ru', contentType: '短视频',
    title: 'Быстрая доставка из Китая — кейс клиента',
    status: '04_小M待剪辑', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小M',
    videoType: '短视频', editLevel: 'B标准', materialId: 'MAT-TLR-001',
    materialLink: 'https://drive.google.com/mock/mat-tlr-001',
    scriptLink: 'https://docs.google.com/mock/script-tlr-001',
    coverRequirements: '俄文标题，物流场景图', subtitleLanguage: '俄文', mDeadline: '2026-05-21',
    riskLevel: '低', aiRiskScore: 14, aiDecision: 'auto_approve',
    nextAssignee: '小S', nextAction: '成片提交后进入小S待终审',
    createdAt: '2026-05-07', updatedAt: '2026-05-13',
  },
  {
    id: 'TLR-002', website: 'tiger-logistics.ru', contentType: 'SEO文章',
    title: 'Как рассчитать стоимость доставки из Китая',
    status: '10_已完成', priority: 'C', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    seoArticleLink: 'https://tiger-logistics.ru/blog/mock-article', crmTags: 'russia_seo',
    hasInquiry: true, inquiryCount: 4,
    riskLevel: '低', aiRiskScore: 12, autoApproved: true,
    approvalRulesHit: ['普通SEO文章', '无价格承诺', 'CTA已配置'],
    aiDecision: 'auto_approve', aiDecisionReason: '普通物流介绍，已自动放行并发布',
    autoApprovalTime: '2026-05-01 09:00',
    opLog: [
      { time: '2026-05-01 09:00', action: 'AI自动放行，进入发布队列', operator: 'AI系统' },
      { time: '2026-05-02 10:00', action: '已发布', operator: '小S' },
      { time: '2026-05-10 08:00', action: '数据回收：展示200次，点击18次，询盘4次', operator: '龙虾' },
    ],
    createdAt: '2026-04-20', updatedAt: '2026-05-10',
  },
  {
    id: 'TLR-003', website: 'tiger-logistics.ru', contentType: 'Landing Page',
    title: 'Экспресс-доставка из Китая — Landing Page',
    status: '06_Vera待审核', priority: 'A', isOverdue: false, needsVeraReview: true, assignedTo: 'Vera',
    targetUrl: '/ekspress-dostavka',
    riskType: 'Landing Page上线前确认 / 含时效承诺',
    reviewLink: 'https://tiger-logistics.ru/mock-preview/lp-express',
    lpBrief: '主打10-15天到俄罗斯，含询价表单', cDeadline: '2026-05-17',
    riskLevel: '高', aiRiskScore: 82, riskLabels: ['时效风险', 'Landing Page上线风险'],
    aiDecision: 'vera_required', aiDecisionReason: 'LP含具体时效数字，必须Vera确认后方可上线',
    nextAssignee: '小C', nextAction: 'Vera确认后小C正式上线',
    opLog: [
      { time: '2026-05-13 09:00', action: '小C页面搭建完成', operator: '小C' },
      { time: '2026-05-13 09:05', action: 'AI风险判断：高风险，强制转Vera', operator: 'AI系统' },
    ],
    createdAt: '2026-05-05', updatedAt: '2026-05-13',
  },
  {
    id: 'TLR-004', website: 'tiger-logistics.ru', contentType: '数据复盘',
    title: '4月数据复盘——tiger-logistics.ru流量分析',
    status: '09_数据待复盘', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    sDeadline: '2026-05-20', riskLevel: '低', aiRiskScore: 6, aiDecision: 'auto_approve',
    nextAssignee: 'Vera', nextAction: '复盘报告完成后发送Vera',
    createdAt: '2026-05-11', updatedAt: '2026-05-13',
  },

  // ── tiger-poisk.ru ──────────────────────────────────────────────────────
  {
    id: 'TPR-001', website: 'tiger-poisk.ru', contentType: '短视频',
    title: 'Поиск товаров на Ozon — как работает Tiger',
    status: '02_小S待审核', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    keywords: 'поиск товаров озон', keywordSource: 'Wordstat', skill: '短视频脚本',
    aiOutputLink: 'https://docs.google.com/mock/ai-tpr-001',
    videoType: '短视频', editLevel: 'B标准', sDeadline: '2026-05-19',
    riskLevel: '低', aiRiskScore: 15, aiDecision: 'auto_approve',
    nextAssignee: '小M', nextAction: '审核通过后交小M剪辑',
    opLog: [{ time: '2026-05-13 11:00', action: 'AI生成脚本', operator: '龙虾' }],
    createdAt: '2026-05-09', updatedAt: '2026-05-13',
  },
  {
    id: 'TPR-002', website: 'tiger-poisk.ru', contentType: '长视频',
    title: '完整Ozon开店教程——新手必看（首次上架）',
    status: '04_小M待剪辑', priority: 'A', isOverdue: true, needsVeraReview: true, assignedTo: '小M',
    videoType: '长视频', editLevel: 'A精剪', materialId: 'MAT-TPR-002',
    materialLink: 'https://drive.google.com/mock/mat-tpr-002',
    scriptLink: 'https://docs.google.com/mock/script-tpr-002',
    coverRequirements: '专业感强，含Ozon logo（注意版权）', subtitleLanguage: '俄文',
    mDeadline: '2026-05-11', riskType: '首次Ozon内容 / A类长视频',
    riskLevel: '高', aiRiskScore: 78, riskLabels: ['首次Ozon内容', 'A类长视频', 'Ozon/WB官方误导风险'],
    aiDecision: 'vera_required', aiDecisionReason: '首次Ozon内容且A类长视频，必须Vera审核',
    nextAssignee: 'Vera', nextAction: '成片完成后需Vera审核',
    opLog: [
      { time: '2026-04-25 09:00', action: '任务创建', operator: '小S' },
      { time: '2026-05-10 17:00', action: '小S终审通过脚本', operator: '小S' },
      { time: '2026-05-11 09:00', action: 'AI风险标记：高风险', operator: 'AI系统' },
    ],
    createdAt: '2026-04-25', updatedAt: '2026-05-11',
  },
  {
    id: 'TPR-003', website: 'tiger-poisk.ru', contentType: 'URL检查',
    title: 'Ozon与WB价格对比页面——URL与SEO检查',
    status: '03_小C待确认URL', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小C',
    targetUrl: '/ozon-wb-price-comparison', urlStatus: '已存在，需更新',
    sitemapStatus: '已收录', gscStatus: '已索引，排名P3', cDeadline: '2026-05-20',
    riskLevel: '低', aiRiskScore: 9, aiDecision: 'auto_approve',
    nextAssignee: '小S', nextAction: '技术检查完成后小S更新文案',
    createdAt: '2026-05-10', updatedAt: '2026-05-12',
  },
  {
    id: 'TPR-004', website: 'tiger-poisk.ru', contentType: 'SEO文章',
    title: 'WB vs Ozon 2026年最新对比——卖家选哪个？',
    status: '08_已发布', priority: 'C', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    seoArticleLink: 'https://tiger-poisk.ru/blog/mock-wb-ozon', crmTags: 'marketplace_seller',
    hasInquiry: true, inquiryCount: 7,
    riskLevel: '低', aiRiskScore: 11, autoApproved: true,
    approvalRulesHit: ['普通对比文章', '无官方误导', '无价格承诺'],
    aiDecision: 'auto_approve', autoApprovalTime: '2026-05-07 18:00',
    opLog: [
      { time: '2026-05-07 18:00', action: 'AI自动放行', operator: 'AI系统' },
      { time: '2026-05-08 09:00', action: '已发布', operator: '小S' },
    ],
    createdAt: '2026-04-30', updatedAt: '2026-05-12',
  },

  // ── oz-logistics.ru ─────────────────────────────────────────────────────
  {
    id: 'OZL-001', website: 'oz-logistics.ru', contentType: '短视频',
    title: 'Ozon FBO vs FBS — в чём разница и что выгоднее',
    status: '01_AI待生成', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '龙虾',
    keywords: 'озон фбо фбс отличие', skill: '短视频脚本+对比图文',
    videoType: '短视频', editLevel: 'B标准', sDeadline: '2026-05-23',
    riskLevel: '低', aiRiskScore: 13, aiDecision: 'auto_approve',
    nextAssignee: '小S', nextAction: 'AI生成脚本后交小S审核',
    createdAt: '2026-05-12', updatedAt: '2026-05-14',
  },
  {
    id: 'OZL-002', website: 'oz-logistics.ru', contentType: 'Landing Page',
    title: 'Ozon清关服务页——含价格与时效（Vera必审）',
    status: '06_Vera待审核', priority: 'A', isOverdue: false, needsVeraReview: true, assignedTo: 'Vera',
    targetUrl: '/tamozhennoe-oformlenie-ozon',
    riskType: '清关/价格/时效相关内容 / Landing Page上线前确认',
    reviewLink: 'https://oz-logistics.ru/mock-preview/customs',
    lpBrief: '含具体清关费率、时效承诺', cDeadline: '2026-05-16',
    riskLevel: '高', aiRiskScore: 90,
    riskLabels: ['清关承诺风险', '价格风险', '时效风险', 'Landing Page上线风险'],
    aiDecision: 'vera_required', aiDecisionReason: '涉及清关/价格/时效三类高风险，强制Vera审核',
    nextAssignee: '小C', nextAction: 'Vera审核通过后立即上线',
    opLog: [
      { time: '2026-05-14 09:00', action: 'AI风险评分：90/100，强制转Vera', operator: 'AI系统' },
    ],
    createdAt: '2026-05-08', updatedAt: '2026-05-14',
  },
  {
    id: 'OZL-003', website: 'oz-logistics.ru', contentType: '素材整理',
    title: 'Ozon仓库实拍素材整理——11批次',
    status: '04_小M待剪辑', priority: 'C', isOverdue: false, needsVeraReview: false, assignedTo: '小M',
    materialId: 'MAT-OZL-003', materialLink: 'https://drive.google.com/mock/mat-ozl-003',
    coverRequirements: '按场景分类：入库、分拣、打包、出库', mDeadline: '2026-05-25',
    riskLevel: '低', aiRiskScore: 5, autoApproved: false,
    approvalRulesHit: ['普通素材整理', '无客户隐私', '无价格信息'],
    aiDecision: 'auto_approve', aiDecisionReason: '普通仓库素材，整理完成后可自动放行',
    nextAssignee: '小S', nextAction: '整理完成后小S确认可用列表',
    createdAt: '2026-05-11', updatedAt: '2026-05-13',
  },
  {
    id: 'OZL-004', website: 'oz-logistics.ru', contentType: 'SEO文章',
    title: 'Ozon全平台运营攻略——从0到月销百万',
    status: '99_暂停/返工', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    keywords: 'озон продавец, продажи на озон', aiOutputLink: 'https://docs.google.com/mock/ai-ozl-004',
    sDeadline: '2026-05-30', blockReason: '等待客户案例数据确认，预计5月20日后重启',
    riskLevel: '中', aiRiskScore: 45, riskLabels: ['客户案例真实性风险'],
    aiDecision: 'vera_required', aiDecisionReason: '需要真实数据，当前数据未确认',
    nextAssignee: '小S', nextAction: '获得数据后继续撰写第三、四章',
    opLog: [
      { time: '2026-05-10 14:00', action: 'Vera标注需要真实案例数据，暂停', operator: 'Vera' },
    ],
    createdAt: '2026-05-01', updatedAt: '2026-05-13',
  },

  // ── Extra tasks (from v1.1) ─────────────────────────────────────────────
  {
    id: 'TLC-005', website: 'tigerlogisticschina.com', contentType: '广告素材',
    title: 'Yandex广告主图制作——5组AB测试素材',
    status: '04_小M待剪辑', priority: 'A', isOverdue: false, needsVeraReview: false, assignedTo: '小M',
    materialId: 'MAT-TLC-005', materialLink: 'https://drive.google.com/mock/mat-tlc-005',
    coverRequirements: '尺寸：1200×628，1:1，9:16，三种版本；俄文文案', mDeadline: '2026-05-18',
    riskLevel: '低', aiRiskScore: 8, aiDecision: 'auto_approve',
    nextAssignee: '小A', nextAction: '素材完成后交小A上传Yandex后台',
    createdAt: '2026-05-12', updatedAt: '2026-05-14',
  },
  {
    id: 'TLR-005', website: 'tiger-logistics.ru', contentType: 'SEO文章',
    title: 'Доставка товаров из Китая под ключ — тарифы 2026',
    status: '02_小S待审核', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    keywords: 'доставка из китая под ключ', skill: 'SEO长文（俄文）',
    aiOutputLink: 'https://docs.google.com/mock/ai-tlr-005', sDeadline: '2026-05-22',
    riskLevel: '中', aiRiskScore: 48, riskLabels: ['价格风险'],
    aiDecision: 'vera_required', aiDecisionReason: '含tарифы(费率)，需人工确认价格准确性',
    nextAssignee: '小C', nextAction: '审核通过后发布',
    createdAt: '2026-05-11', updatedAt: '2026-05-14',
  },
  {
    id: 'TPR-005', website: 'tiger-poisk.ru', contentType: 'Landing Page',
    title: 'Поиск и закупка товаров на Ozon — LP',
    status: '03_小C待确认URL', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小C',
    targetUrl: '/ozon-sourcing-service', urlStatus: '待创建', needsNewPage: true,
    lpBrief: '主打代找Ozon爆款商品，含WhatsApp询价入口',
    formStatus: '待配置', sitemapStatus: '待更新', gscStatus: '待提交', cDeadline: '2026-05-21',
    riskLevel: '中', aiRiskScore: 30, riskLabels: ['页面链接风险'],
    aiDecision: 'vera_required', aiDecisionReason: 'Landing Page上线前需Vera确认',
    nextAssignee: '小A', nextAction: '上线后小A配置TikTok广告落地页',
    createdAt: '2026-05-11', updatedAt: '2026-05-14',
  },
  {
    id: 'OZL-005', website: 'oz-logistics.ru', contentType: '发布文案',
    title: 'VK社群——Ozon清关服务推广文案',
    status: '07_待发布', priority: 'C', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    utmLink: 'https://oz-logistics.ru/customs?utm_source=vk&utm_medium=social',
    cta: '免费咨询清关流程', crmTags: 'ozon_customs, vk_social', sDeadline: '2026-05-16',
    riskLevel: '低', aiRiskScore: 10, autoApproved: true,
    approvalRulesHit: ['普通社媒文案', 'UTM已配置', 'CTA已配置', 'CRM标签已配置'],
    aiDecision: 'auto_approve', autoApprovalTime: '2026-05-14 20:00',
    nextAssignee: '小A', nextAction: '文案发布后配合VK广告投放',
    opLog: [
      { time: '2026-05-14 20:00', action: 'AI自动放行，进入发布队列', operator: 'AI系统' },
    ],
    createdAt: '2026-05-12', updatedAt: '2026-05-14',
  },

  // ── Ad tasks (existing) ─────────────────────────────────────────────────
  {
    id: 'TSC-AD-001', website: 'tigersourcingchina.com', contentType: '广告素材',
    title: 'Google Ads — 义乌采购代理服务投放',
    status: '08_已发布', priority: 'A', isOverdue: false, needsVeraReview: false, assignedTo: '小A',
    isAdTask: true, adPlatform: 'Google Ads', adRegion: '俄罗斯、独联体、东欧',
    adObjective: '询盘获取（表单提交）',
    adMaterialLink: 'https://drive.google.com/mock/ad-mat-tsc-001',
    targetUrl: '/yiwu-sourcing-agent',
    utmLink: 'https://tigersourcingchina.com/yiwu-sourcing-agent?utm_source=google&utm_medium=cpc',
    budget: 5000, spent: 2340, impressions: 45200, clicks: 892, ctr: 1.98, cpc: 2.62,
    whatsappClicks: 34, formSubmits: 18, validInquiries: 10,
    inquiries: 12, cpl: 195, conversionRate: 1.34, adStatus: '观察中', aDeadline: '2026-05-31',
    dataFeedback: 'CPL偏高，建议测试新文案。移动端CTR比桌面端高42%。',
    adPerformanceSummary: '展示量正常，CTR接近行业均值，但CPL $195高于目标$150。移动端表现明显优于桌面端。',
    adIssues: '文案标题点击率低，落地页表单完成率仅60%，WhatsApp按钮位置不明显。',
    adRecommendations: '1) 新建2组A/B测试文案；2) 移动优先布局调整LP；3) WhatsApp按钮上移至首屏。',
    hasInquiry: true, inquiryCount: 12, needsCopyChange: true,
    riskLevel: '中', aiRiskScore: 35, riskLabels: ['广告预算风险'],
    adNextAction: '提交A/B测试文案至龙虾，同步通知小C优化LP表单位置',
    nextAssignee: '小S', nextAction: '优化广告文案，A/B测试两组新标题',
    opLog: [
      { time: '2026-05-06 09:00', action: '广告开始投放', operator: '小A' },
      { time: '2026-05-13 16:00', action: '提交周数据报告', operator: '小A' },
    ],
    createdAt: '2026-05-06', updatedAt: '2026-05-13',
  },
  {
    id: 'TLC-AD-001', website: 'tigerlogisticschina.com', contentType: '广告素材',
    title: 'Yandex Direct — 中俄物流关键词投放',
    status: '08_已发布', priority: 'A', isOverdue: false, needsVeraReview: false, assignedTo: '小A',
    isAdTask: true, adPlatform: 'Yandex Direct', adRegion: '俄罗斯全境',
    adObjective: '询盘获取 + 品牌曝光',
    adMaterialLink: 'https://drive.google.com/mock/ad-mat-tlc-001',
    targetUrl: '/ekspress-dostavka',
    budget: 3000, spent: 1820, impressions: 62400, clicks: 1247, ctr: 2.0, cpc: 1.46,
    whatsappClicks: 12, formSubmits: 6, validInquiries: 6,
    inquiries: 8, cpl: 227.5, conversionRate: 0.64, adStatus: '需优化', aDeadline: '2026-05-31',
    dataFeedback: '展示量大但转化低，落地页跳出率78%，需要优化LP。',
    adPerformanceSummary: '展示量和点击量良好，但落地页跳出率达78%，导致转化率仅0.64%，CPL远高于目标。',
    adIssues: '落地页加载速度慢（移动端3.8秒），首屏缺乏明确CTA，表单字段过多。',
    adRecommendations: '1) 压缩LP图片资源；2) 首屏增加"立即咨询"按钮；3) 表单缩减至3个字段。',
    veraAdDecision: '同意优化LP，暂缓加预算，待LP改版后再评估。',
    veraAdDecisionAt: '2026-05-14',
    hasInquiry: true, inquiryCount: 8, needsLpChange: true,
    riskLevel: '中', aiRiskScore: 42, riskLabels: ['广告预算风险'],
    adNextAction: '通知小C紧急优化落地页，预计5月20日前完成',
    nextAssignee: '小C', nextAction: '优化落地页转化率，小A收紧关键词匹配',
    opLog: [
      { time: '2026-05-05 09:00', action: '广告开始投放', operator: '小A' },
      { time: '2026-05-13 15:00', action: '提交优化建议，等待Vera决定', operator: '小A' },
      { time: '2026-05-14 10:00', action: 'Vera确认：优化LP后再加预算', operator: 'Vera' },
    ],
    createdAt: '2026-05-05', updatedAt: '2026-05-14',
  },
  {
    id: 'TLR-AD-001', website: 'tiger-logistics.ru', contentType: '广告素材',
    title: 'VK Ads — tiger-logistics.ru 品牌推广',
    status: '02_小S待审核', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小A',
    isAdTask: true, adPlatform: 'VK Ads', adRegion: '俄罗斯',
    adObjective: '品牌曝光 + 网站流量',
    budget: 2000, spent: 0, adStatus: '待审核素材', aDeadline: '2026-05-19',
    riskLevel: '低', aiRiskScore: 15,
    adNextAction: '等待小M提供素材后上传VK后台，提交审核',
    nextAssignee: '小M', nextAction: '等待小M提供素材后上传VK后台审核',
    createdAt: '2026-05-10', updatedAt: '2026-05-14',
  },
  {
    id: 'TPR-AD-001', website: 'tiger-poisk.ru', contentType: '广告素材',
    title: 'TikTok Ads — Ozon选品服务短视频广告',
    status: '08_已发布', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小A',
    isAdTask: true, adPlatform: 'TikTok Ads', adRegion: '俄罗斯 + 东欧',
    adObjective: '品牌认知 + 引流至落地页',
    adMaterialLink: 'https://drive.google.com/mock/ad-mat-tpr-001',
    targetUrl: '/ozon-sourcing-service',
    budget: 1500, spent: 685, impressions: 84600, clicks: 618, ctr: 0.73, cpc: 1.11,
    views: 52400, cpv: 0.013, whatsappClicks: 4, formSubmits: 2, validInquiries: 2,
    inquiries: 3, cpl: 228.3, conversionRate: 0.49, adStatus: '投放中', aDeadline: '2026-05-28',
    dataFeedback: 'CTR偏低0.73%，视频完播率仅31%，建议优化视频前3秒。',
    adPerformanceSummary: '视频展示量84,600，但完播率仅31%，导致点击少。CPV $0.013尚可，核心问题在前3秒留存。',
    adIssues: '视频前3秒无产品/服务画面，用户流失率高；文案缺乏俄文本土化表述。',
    adRecommendations: '1) 重制视频：前3秒直接展示"从中国发货到俄罗斯"画面；2) 加入俄文字幕；3) 文案本土化。',
    hasInquiry: true, inquiryCount: 3, needsVideoChange: true,
    riskLevel: '中', aiRiskScore: 38,
    adNextAction: '通知小M重制视频，龙虾协助优化俄文文案',
    nextAssignee: '小M', nextAction: '重制视频开头前3秒',
    opLog: [
      { time: '2026-05-07 09:00', action: '广告开始投放', operator: '小A' },
      { time: '2026-05-13 14:00', action: '周数据汇总，发现完播率问题', operator: '小A' },
    ],
    createdAt: '2026-05-07', updatedAt: '2026-05-13',
  },
  {
    id: 'OZL-AD-001', website: 'oz-logistics.ru', contentType: '广告素材',
    title: 'YouTube Ads — Ozon物流教程前贴片广告',
    status: '99_暂停/返工', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小A',
    isAdTask: true, adPlatform: 'YouTube Ads', adRegion: '俄罗斯',
    adObjective: '品牌认知 + 视频观看',
    adMaterialLink: 'https://drive.google.com/mock/ad-mat-ozl-001',
    targetUrl: '/tamozhennoe-oformlenie-ozon',
    budget: 1200, spent: 423, impressions: 18900, clicks: 127, ctr: 0.67, cpc: 3.33,
    views: 9840, cpv: 0.043, whatsappClicks: 3, formSubmits: 1, validInquiries: 2,
    inquiries: 2, cpl: 211.5, adStatus: '暂停', aDeadline: '2026-06-01',
    blockReason: '落地页尚未获得Vera审核通过，广告暂停投放',
    dataFeedback: '广告本身数据尚可，主要问题是落地页未上线。',
    adPerformanceSummary: '广告素材表现正常，前贴片完播率52%，高于TikTok。问题在于落地页未通过Vera审核，转化路径断裂。',
    adIssues: '落地页涉及清关承诺内容，Vera审核暂未通过；期间广告继续消耗预算导致浪费。',
    adRecommendations: '暂停广告等待LP审核；LP修改后移除具体清关时效承诺改为"联系咨询"。',
    hasInquiry: true, inquiryCount: 2, shouldPauseAd: true,
    riskLevel: '中', aiRiskScore: 48,
    adNextAction: '等待Vera审核LP，通过后立即恢复投放',
    nextAssignee: 'Vera', nextAction: 'Vera确认落地页后恢复投放',
    opLog: [
      { time: '2026-05-09 09:00', action: '广告开始投放', operator: '小A' },
      { time: '2026-05-13 11:00', action: '发现落地页未审核，主动暂停', operator: '小A' },
    ],
    createdAt: '2026-05-09', updatedAt: '2026-05-13',
  },
  {
    id: 'TSC-AD-002', website: 'tigersourcingchina.com', contentType: '广告素材',
    title: 'Meta Ads — 采购服务Facebook+Instagram投放',
    status: '01_AI待生成', priority: 'C', isOverdue: false, needsVeraReview: false, assignedTo: '小A',
    isAdTask: true, adPlatform: 'Meta Ads', adRegion: '东南亚 + 中东',
    adObjective: '线索收集（Lead Ads）', budget: 2000, spent: 0, adStatus: '待建广告',
    riskLevel: '低', aiRiskScore: 20,
    adNextAction: '确认广告文案方向和受众定向后建广告，预算需Vera确认',
    nextAssignee: '小S', nextAction: '确认广告文案方向和受众定向后开始建广告',
    createdAt: '2026-05-14', updatedAt: '2026-05-14',
  },
  {
    id: 'TSC-AD-003', website: 'tigersourcingchina.com', contentType: '广告预算',
    title: 'Google Ads — 义乌采购服务放大投放申请',
    status: '06_Vera待审核', priority: 'A', isOverdue: false, needsVeraReview: true, assignedTo: 'Vera',
    isAdTask: true, isBudgetTask: true, adPlatform: 'Google Ads', adRegion: '俄罗斯、独联体',
    adObjective: '放大效果好的询盘广告',
    budget: 5000, currentBudget: 5000, proposedBudget: 9000,
    budgetChangeType: '扩大投放', budgetStatus: '等待Vera确认预算',
    adStatus: '等待Vera确认预算',
    budgetNote: '本月Google Ads CPL $195，近两周数据改善趋势明显（-18%），建议从$5k加至$9k放大跑量。',
    riskLevel: '中', aiRiskScore: 50, riskLabels: ['广告预算风险'],
    aiDecision: 'vera_required', aiDecisionReason: '广告预算增加必须经Vera确认',
    adNextAction: '等待Vera审批，通过后小A立即在Google后台调整预算上限',
    nextAssignee: 'Vera', nextAction: 'Vera确认预算后小A执行',
    opLog: [
      { time: '2026-05-15 09:00', action: 'AI建议预算：$9,000/月', operator: 'AI系统' },
      { time: '2026-05-15 09:05', action: '预算申请提交Vera审核', operator: '小A' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },

  // ════════════════════════════════════════════════════════════════════════
  // PHASE 4 NEW TASKS
  // ════════════════════════════════════════════════════════════════════════

  // ── LOW RISK — Auto-approved (5 new) ────────────────────────────────────
  {
    id: 'Q-LOW-001', website: 'tigersourcingchina.com', contentType: '短视频',
    title: '义乌市场仓库实拍——C类快剪日常素材',
    status: '12_自动放行', priority: 'C', isOverdue: false, needsVeraReview: false, assignedTo: '小M',
    videoType: '短视频', editLevel: 'C快剪', materialId: 'MAT-Q001',
    materialLink: 'https://drive.google.com/mock/mat-q001',
    subtitleLanguage: '俄文', mDeadline: '2026-05-16',
    riskLevel: '低', aiRiskScore: 8, autoApproved: true,
    approvalRulesHit: ['C类快剪', '普通仓库素材', '无价格信息', '无客户隐私', '无时效承诺'],
    aiDecision: 'auto_approve', aiDecisionReason: '满足全部低风险放行条件，AI自动放行',
    autoApprovalTime: '2026-05-15 10:30',
    cta: '联系Tiger采购团队', crmTags: 'sourcing_lead',
    utmLink: 'https://tigersourcingchina.com?utm_source=youtube&utm_medium=organic&utm_campaign=warehouse',
    nextAssignee: '小S', nextAction: '已进入发布队列，待小S安排发布时间',
    opLog: [
      { time: '2026-05-15 08:00', action: '龙虾生成脚本', operator: '龙虾' },
      { time: '2026-05-15 09:00', action: '小M完成C快剪', operator: '小M' },
      { time: '2026-05-15 10:30', action: 'AI风险评估完成：低风险(8/100)', operator: 'AI系统' },
      { time: '2026-05-15 10:30', action: 'AI自动放行，进入发布队列', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },
  {
    id: 'Q-LOW-002', website: 'tigerlogisticschina.com', contentType: '发布文案',
    title: '劳动节限时优惠——中俄物流五折活动文案',
    status: '07_待发布', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    skill: '活动文案', aiOutputLink: 'https://docs.google.com/mock/ai-q002',
    cta: '立即咨询优惠运价', crmTags: 'promo_holiday, china_russia',
    utmLink: 'https://tigerlogisticschina.com?utm_source=wechat&utm_medium=social&utm_campaign=labor_day',
    sDeadline: '2026-05-17',
    riskLevel: '低', aiRiskScore: 12, autoApproved: true,
    approvalRulesHit: ['普通促销文案', '无固定时效承诺', '无价格保证', 'UTM已配置', 'CTA已配置', 'CRM标签已配置'],
    aiDecision: 'auto_approve', aiDecisionReason: '普通节日促销文案，全部放行条件满足',
    autoApprovalTime: '2026-05-15 09:00',
    nextAssignee: '小A', nextAction: '配合社媒广告投放',
    opLog: [
      { time: '2026-05-15 08:00', action: '龙虾生成文案初稿', operator: '龙虾' },
      { time: '2026-05-15 09:00', action: 'AI基础风险检查通过，自动放行', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },
  {
    id: 'Q-LOW-003', website: 'tiger-logistics.ru', contentType: '短视频',
    title: '广交会现场直击——Tiger物流展位实拍',
    status: '12_自动放行', priority: 'C', isOverdue: false, needsVeraReview: false, assignedTo: '小M',
    videoType: '短视频', editLevel: 'C快剪',
    materialLink: 'https://drive.google.com/mock/mat-q003',
    subtitleLanguage: '俄文', mDeadline: '2026-05-16',
    cta: 'Узнать подробнее', crmTags: 'russia_branding',
    utmLink: 'https://tiger-logistics.ru?utm_source=vk&utm_medium=social&utm_campaign=canton_fair',
    riskLevel: '低', aiRiskScore: 5, autoApproved: true,
    approvalRulesHit: ['C类快剪', '展会现场素材', '无价格/时效/清关', '无客户隐私'],
    aiDecision: 'auto_approve', autoApprovalTime: '2026-05-15 11:00',
    nextAssignee: '小S', nextAction: '已自动放行，待安排发布',
    opLog: [
      { time: '2026-05-15 11:00', action: 'AI自动放行，风险分5/100', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },
  {
    id: 'Q-LOW-004', website: 'tiger-poisk.ru', contentType: 'SEO文章',
    title: 'Как зарегистрироваться на Ozon — пошаговая инструкция',
    status: '12_自动放行', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    skill: 'SEO长文（俄文）', aiOutputLink: 'https://docs.google.com/mock/ai-q004',
    keywords: 'регистрация озон, как зарегистрироваться на озон',
    cta: 'Получить консультацию', crmTags: 'ozon_seller, top_funnel',
    utmLink: 'https://tiger-poisk.ru/ozon-registration?utm_source=organic',
    sDeadline: '2026-05-16',
    riskLevel: '低', aiRiskScore: 18, autoApproved: true,
    approvalRulesHit: ['普通使用说明类文章', '不涉及价格', '非首次Ozon内容', '无官方误导'],
    aiDecision: 'auto_approve', autoApprovalTime: '2026-05-15 10:00',
    nextAssignee: '小C', nextAction: '小C确认URL后发布',
    opLog: [
      { time: '2026-05-15 09:00', action: 'AI生成初稿', operator: '龙虾' },
      { time: '2026-05-15 10:00', action: 'AI风险评估：18/100，自动放行', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },
  {
    id: 'Q-LOW-005', website: 'oz-logistics.ru', contentType: '短视频',
    title: 'Ozon仓库打包流程——产品展示C快剪',
    status: '12_自动放行', priority: 'C', isOverdue: false, needsVeraReview: false, assignedTo: '小M',
    videoType: '短视频', editLevel: 'C快剪',
    materialLink: 'https://drive.google.com/mock/mat-q005',
    subtitleLanguage: '俄文', mDeadline: '2026-05-16',
    cta: 'Узнать стоимость', crmTags: 'ozon_logistics',
    utmLink: 'https://oz-logistics.ru?utm_source=tiktok&utm_medium=organic',
    riskLevel: '低', aiRiskScore: 3, autoApproved: true,
    approvalRulesHit: ['C类快剪', '产品展示类', '不涉及价格/时效/清关', '无客户信息'],
    aiDecision: 'auto_approve', autoApprovalTime: '2026-05-15 12:00',
    nextAssignee: '小S', nextAction: '已自动放行，待发布',
    opLog: [
      { time: '2026-05-15 12:00', action: 'AI自动放行，风险分3/100，命中5条放行规则', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },

  // ── HIGH RISK — Vera required (3 new) ───────────────────────────────────
  {
    id: 'Q-HIGH-001', website: 'tigersourcingchina.com', contentType: '客户案例',
    title: '上海客户采购案例——工厂直采省40万（含客户正脸视频）',
    status: '06_Vera待审核', priority: 'A', isOverdue: false, needsVeraReview: true, assignedTo: 'Vera',
    finalVideoLink: 'https://drive.google.com/mock/case-q-high-001',
    reviewLink: 'https://drive.google.com/mock/case-q-high-001',
    riskType: '客户案例 / 含客户正脸 / 客户真实信息',
    riskLevel: '高', aiRiskScore: 92,
    riskLabels: ['客户隐私风险', '客户案例真实性风险', '品牌风险'],
    aiDecision: 'vera_required',
    aiDecisionReason: '客户案例视频含客户正脸，且金额(40万)需要验证真实性，必须Vera审核',
    cta: '了解同类采购服务', crmTags: 'customer_case, high_value',
    nextAssignee: '小S', nextAction: 'Vera确认客户授权后方可发布',
    completionCriteria: '确认客户已签署内容授权书，数据已核实，敏感信息已处理',
    opLog: [
      { time: '2026-05-15 08:00', action: 'AI风险评分：92/100，强制转Vera', operator: 'AI系统' },
      { time: '2026-05-15 08:01', action: '命中规则：客户案例+客户正脸+高金额', operator: 'AI系统' },
    ],
    createdAt: '2026-05-14', updatedAt: '2026-05-15',
  },
  {
    id: 'Q-HIGH-002', website: 'tigerlogisticschina.com', contentType: '长视频',
    title: 'Tiger物流服务全面介绍——官网核心推广视频（A级）',
    status: '06_Vera待审核', priority: 'A', isOverdue: false, needsVeraReview: true, assignedTo: 'Vera',
    videoType: '长视频', editLevel: 'A精剪',
    finalVideoLink: 'https://drive.google.com/mock/main-video-q-high-002',
    reviewLink: 'https://drive.google.com/mock/main-video-q-high-002',
    riskType: 'A类长视频 / 官网核心页面',
    riskLevel: '高', aiRiskScore: 80,
    riskLabels: ['A类长视频', '品牌风险', '法务风险'],
    aiDecision: 'vera_required',
    aiDecisionReason: 'A类长视频且作为官网核心推广视频，品牌风险高，必须Vera最终确认',
    mDeadline: '2026-05-18',
    nextAssignee: '小S', nextAction: 'Vera审核通过后上传YouTube官方频道',
    opLog: [
      { time: '2026-05-15 09:00', action: '小M提交成片', operator: '小M' },
      { time: '2026-05-15 09:05', action: 'AI识别：A类长视频+官网核心，强制Vera审核', operator: 'AI系统' },
    ],
    createdAt: '2026-05-10', updatedAt: '2026-05-15',
  },

  // ── SYSTEM INTERCEPTED (3 new) ──────────────────────────────────────────
  {
    id: 'Q-INT-001', website: 'tigersourcingchina.com', contentType: 'SEO文章',
    title: '中国清关服务——100%清关保证，零风险采购',
    status: '11_已拦截', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '小S',
    skill: 'SEO长文', aiOutputLink: 'https://docs.google.com/mock/ai-q-int-001',
    riskLevel: '高', aiRiskScore: 100,
    riskLabels: ['清关承诺风险', '法务风险'],
    isIntercepted: true,
    interceptReasons: ['出现"100%清关保证"违规承诺', '出现"零风险"误导性表述'],
    aiDecision: 'intercept',
    aiDecisionReason: 'AI检测到"100%清关"和"零风险"等违规表述，不符合合规要求，自动拦截',
    nextAssignee: '龙虾', nextAction: '退回龙虾重写，删除所有绝对保证类表述',
    opLog: [
      { time: '2026-05-15 09:00', action: '龙虾生成初稿', operator: '龙虾' },
      { time: '2026-05-15 09:02', action: 'AI拦截：检测到"100%清关保证"违规词', operator: 'AI系统' },
      { time: '2026-05-15 09:02', action: '内容已拦截，不得进入发布队列', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },
  {
    id: 'Q-INT-002', website: 'tigerlogisticschina.com', contentType: '短视频',
    title: 'Tiger物流——保证全程最低价，比同行便宜30%',
    status: '11_已拦截', priority: 'B', isOverdue: false, needsVeraReview: false, assignedTo: '龙虾',
    skill: '短视频脚本', videoType: '短视频',
    riskLevel: '高', aiRiskScore: 100,
    riskLabels: ['价格风险', '法务风险', '品牌风险'],
    isIntercepted: true,
    interceptReasons: ['出现"保证最低价"违规承诺', '出现"比同行便宜30%"未经核实的比较性声明'],
    aiDecision: 'intercept',
    aiDecisionReason: 'AI检测到价格保证类违规表述，已自动拦截，禁止进入任何队列',
    nextAssignee: '龙虾', nextAction: '退回龙虾重写，删除所有价格保证和比较性声明',
    opLog: [
      { time: '2026-05-15 10:00', action: '龙虾生成脚本初稿', operator: '龙虾' },
      { time: '2026-05-15 10:01', action: 'AI拦截：检测到"保证最低价"', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },
  {
    id: 'Q-INT-003', website: 'tiger-poisk.ru', contentType: 'Landing Page',
    title: 'Ozon代运营服务落地页——准备发布',
    status: '11_已拦截', priority: 'A', isOverdue: false, needsVeraReview: false, assignedTo: '小C',
    targetUrl: '/ozon-management-service', urlStatus: '已创建',
    riskLevel: '高', aiRiskScore: 75,
    riskLabels: ['页面链接风险'],
    isIntercepted: true,
    interceptReasons: ['UTM链接缺失，无法追踪流量来源', 'CTA文本缺失', 'CRM标签未配置', 'Landing Page上线前检查未通过'],
    aiDecision: 'intercept',
    aiDecisionReason: 'UTM/CTA/CRM三项关键字段缺失，拦截，退回小C补全后重新提交',
    nextAssignee: '小C', nextAction: '补全UTM链接、CTA文本和CRM标签后重新提交',
    opLog: [
      { time: '2026-05-15 11:00', action: '小C提交Landing Page发布申请', operator: '小C' },
      { time: '2026-05-15 11:01', action: 'AI检查：UTM缺失+CTA缺失+CRM标签缺失', operator: 'AI系统' },
      { time: '2026-05-15 11:01', action: '系统拦截，退回小C', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },

  // ── BUDGET CONFIRMATION — Vera required (4 new) ─────────────────────────
  {
    id: 'BUD-001', website: 'tigersourcingchina.com', contentType: '广告预算',
    title: 'Google Ads — 申请加预算 $3,000（采购服务夏季投放）',
    status: '06_Vera待审核', priority: 'A', isOverdue: false, needsVeraReview: true, assignedTo: 'Vera',
    isAdTask: true, isBudgetTask: true, adPlatform: 'Google Ads',
    adRegion: '俄罗斯、独联体', adObjective: '询盘获取',
    budgetChangeType: '加预算', budgetStatus: '等待Vera确认预算',
    currentBudget: 5000, proposedBudget: 8000,
    budgetNote: '5月询盘量增加，Google Ads ROI表现良好(CPL $195)，建议增加$3,000预算扩大投放规模。预计每月额外增加8-12个询盘。',
    adStatus: '等待Vera确认预算',
    riskLevel: '高', aiRiskScore: 70, riskLabels: ['广告预算风险'],
    aiDecision: 'vera_required',
    aiDecisionReason: '预算变化必须Vera确认，AI不可自动批准',
    nextAssignee: 'Vera', nextAction: 'Vera确认预算后小A执行调整',
    opLog: [
      { time: '2026-05-15 09:00', action: '小A提交加预算申请', operator: '小A' },
      { time: '2026-05-15 09:01', action: 'AI识别：预算变化，强制转Vera确认', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },
  {
    id: 'BUD-002', website: 'tigerlogisticschina.com', contentType: '广告预算',
    title: 'Yandex Direct — 新建广告计划，月预算 $4,000',
    status: '06_Vera待审核', priority: 'A', isOverdue: false, needsVeraReview: true, assignedTo: 'Vera',
    isAdTask: true, isBudgetTask: true, adPlatform: 'Yandex Direct',
    adRegion: '俄罗斯全境', adObjective: '品牌曝光+询盘',
    budgetChangeType: '新建预算', budgetStatus: '等待Vera确认预算',
    currentBudget: 0, proposedBudget: 4000,
    budgetNote: '新建Yandex广告计划，覆盖"中俄货运"核心关键词。预计CPL $150-200，月询盘10-15个。需Vera确认预算后小A开始建立广告账户。',
    adStatus: '等待Vera确认预算',
    riskLevel: '高', aiRiskScore: 65, riskLabels: ['广告预算风险'],
    aiDecision: 'vera_required', aiDecisionReason: '新建广告预算，必须Vera审批',
    nextAssignee: 'Vera', nextAction: 'Vera批准后小A建立广告账户',
    opLog: [
      { time: '2026-05-15 10:00', action: '小A提交新建广告预算申请', operator: '小A' },
      { time: '2026-05-15 10:01', action: 'AI路由：新建预算，强制Vera审核', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },
  {
    id: 'BUD-003', website: 'tiger-poisk.ru', contentType: '广告预算',
    title: 'TikTok Ads — 扩大投放至中亚5国，追加预算$2,000',
    status: '06_Vera待审核', priority: 'B', isOverdue: false, needsVeraReview: true, assignedTo: 'Vera',
    isAdTask: true, isBudgetTask: true, adPlatform: 'TikTok Ads',
    adRegion: '俄罗斯 + 哈萨克斯坦 + 乌兹别克斯坦 + 白俄罗斯 + 吉尔吉斯斯坦',
    adObjective: '品牌认知+引流',
    budgetChangeType: '扩大投放', budgetStatus: '等待Vera确认预算',
    currentBudget: 1500, proposedBudget: 3500,
    budgetNote: 'TikTok在中亚市场活跃度高，建议扩大至中亚5国。需新增俄语广告素材。预计CPM降低20%，曝光量增加3倍。',
    adStatus: '等待Vera确认预算',
    riskLevel: '高', aiRiskScore: 60, riskLabels: ['广告预算风险'],
    aiDecision: 'vera_required', aiDecisionReason: '投放地区扩大+预算增加，双重变化必须Vera确认',
    nextAssignee: 'Vera', nextAction: 'Vera确认后小A配置新投放地区',
    opLog: [
      { time: '2026-05-15 11:00', action: '小A提交扩大投放申请', operator: '小A' },
      { time: '2026-05-15 11:01', action: 'AI路由：投放地区变化+预算增加，强制Vera审核', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },
  {
    id: 'BUD-004', website: 'oz-logistics.ru', contentType: '广告预算',
    title: 'VK Ads — 暂停所有广告，节省预算等待新素材',
    status: '06_Vera待审核', priority: 'B', isOverdue: false, needsVeraReview: true, assignedTo: 'Vera',
    isAdTask: true, isBudgetTask: true, adPlatform: 'VK Ads',
    adRegion: '俄罗斯', adObjective: '品牌曝光',
    budgetChangeType: '暂停预算', budgetStatus: '等待Vera确认预算',
    currentBudget: 1500, proposedBudget: 0,
    budgetNote: '当前VK广告素材效果不佳(CTR 0.4%)，建议暂停所有广告，等待新素材(预计5月20日完成)后重启。可节省约$800。',
    adStatus: '等待Vera确认预算',
    riskLevel: '高', aiRiskScore: 55, riskLabels: ['广告预算风险'],
    aiDecision: 'vera_required', aiDecisionReason: '广告暂停操作必须Vera确认，防止误操作',
    nextAssignee: 'Vera', nextAction: 'Vera确认暂停后，小A执行暂停操作',
    opLog: [
      { time: '2026-05-15 14:00', action: '小A建议暂停VK广告', operator: '小A' },
      { time: '2026-05-15 14:01', action: 'AI路由：广告暂停涉及预算变化，强制Vera确认', operator: 'AI系统' },
    ],
    createdAt: '2026-05-15', updatedAt: '2026-05-15',
  },
];

// ─── Filter helper ─────────────────────────────────────────────────────────

export function filterTasks(tasks: Task[], filters: Partial<FilterState>): Task[] {
  return tasks.filter((t) => {
    if (filters.assignedTo && filters.assignedTo !== 'all' && t.assignedTo !== filters.assignedTo) return false;
    if (filters.website && filters.website !== 'all' && t.website !== filters.website) return false;
    if (filters.contentType && filters.contentType !== 'all' && t.contentType !== filters.contentType) return false;
    if (filters.status && filters.status !== 'all' && t.status !== filters.status) return false;
    if (filters.priority && filters.priority !== 'all' && t.priority !== filters.priority) return false;
    if (filters.isOverdue === true && !t.isOverdue) return false;
    if (filters.needsVeraReview === true && !t.needsVeraReview) return false;
    return true;
  });
}

// ─── Public API ────────────────────────────────────────────────────────────

export async function getTasks(): Promise<Task[]> {
  // TODO: replace with real GAS API call
  return Promise.resolve(MOCK_TASKS);
}

export async function updateTaskField(id: string, field: string, value: unknown): Promise<void> {
  // TODO: replace with real GAS API call
  console.log('[taskApi] updateTaskField', { id, field, value });
  return Promise.resolve();
}

export { MOCK_TASKS };
