import assert from 'node:assert/strict';
import test from 'node:test';
import { ActionError, applyOutreachAction } from '../src/outreach/engine';
import { initialLab } from '../src/outreach/model';

const boss={id:'person_boss',email:'boss@example.invalid',name:'老板',role:'boss' as const};
const sales={id:'person_sales',email:'sales@example.invalid',name:'业务员',role:'sales' as const};
const codex={id:'service_codex',email:'',name:'Codex',role:'codex' as const};
const at='2026-09-12T00:00:00.000Z';

test('draft is preserved and Codex cannot silently start or work',()=>{const lab=initialLab(at);assert.equal(lab.config.status,'draft');assert.throws(()=>applyOutreachAction(lab,codex,{action:'lead.import',leads:[{}]},at),(error:unknown)=>error instanceof ActionError&&error.status===403)});
test('only boss starts the 30-day scope and CAS protects changes',()=>{const lab=initialLab(at);assert.throws(()=>applyOutreachAction(lab,sales,{action:'config',config:{}},at),/老板/);const started=applyOutreachAction(lab,boss,{action:'config',baseConfig:lab.config,start:true,config:{...lab.config,startDate:'2026-09-12'}},at).lab;assert.equal(started.config.status,'active');assert.equal(started.tasks.find(x=>x.id==='setup-scope')?.status,'accepted');assert.throws(()=>applyOutreachAction(started,boss,{action:'config',baseConfig:lab.config,config:started.config},at),(error:unknown)=>error instanceof ActionError&&error.status===409)});
test('candidate, contact and qualified stages require real evidence',()=>{let lab=applyOutreachAction(initialLab(at),boss,{action:'config',start:true,baseConfig:initialLab(at).config,config:{...initialLab(at).config,startDate:'2026-09-12'}},at).lab;lab=applyOutreachAction(lab,codex,{action:'lead.create',lead:{company:'Example Parts',market:'RU',region:lab.config.ruRegion,product:'轴',fitReason:'官网公开维修业务'}},at).lab;const lead=lab.leads[0];assert.equal(lead.stage,'new');assert.throws(()=>applyOutreachAction(lab,sales,{action:'lead.advance',id:lead.id,baseLead:lead,fields:{}},at),/联系人/);lab=applyOutreachAction(lab,sales,{action:'lead.update',id:lead.id,baseLead:lead,fields:{contact:'Public contact',assigneeId:sales.id,assignee:sales.name}},at).lab;const verified=applyOutreachAction(lab,sales,{action:'lead.advance',id:lead.id,baseLead:lab.leads[0],fields:{}},at).lab;assert.equal(verified.leads[0].stage,'verified');assert.throws(()=>applyOutreachAction(verified,sales,{action:'lead.advance',id:lead.id,baseLead:verified.leads[0],fields:{}},at),/实际联系/)});
test('Codex cannot self-accept and stale task updates conflict',()=>{let lab=applyOutreachAction(initialLab(at),boss,{action:'config',start:true,baseConfig:initialLab(at).config,config:{...initialLab(at).config,startDate:'2026-09-12'}},at).lab;const task=lab.tasks.find(x=>x.id==='setup-list')!;lab=applyOutreachAction(lab,codex,{action:'task.status',id:task.id,status:'running',baseTaskUpdatedAt:task.updatedAt},'2026-09-12T00:01:00.000Z').lab;const running=lab.tasks.find(x=>x.id===task.id)!;lab=applyOutreachAction(lab,codex,{action:'task.status',id:task.id,status:'submitted',result:'20 家候选企业及来源',baseTaskUpdatedAt:running.updatedAt},'2026-09-12T00:02:00.000Z').lab;const submitted=lab.tasks.find(x=>x.id===task.id)!;assert.throws(()=>applyOutreachAction(lab,codex,{action:'task.status',id:task.id,status:'accepted',baseTaskUpdatedAt:submitted.updatedAt},at),/不能自行验收/);assert.throws(()=>applyOutreachAction(lab,sales,{action:'task.status',id:task.id,status:'accepted',baseTaskUpdatedAt:running.updatedAt},at),(error:unknown)=>error instanceof ActionError&&error.status===409)});
