import {FormEvent,useEffect,useMemo,useState,type ReactNode} from "react";
import {AlertTriangle,CheckCircle2,FileUp,RefreshCw,Search,Send,Target,Users} from "lucide-react";
import type {Viewer} from "../app/AppShell";
import {readOutreach,startOutreachTask,submitOutreachEvent,uploadOutreachAttachment,type OutreachSnapshot,type OutreachTask} from "./api";
import "./outreach.css";

const progressLabels:Record<string,string>={uncontacted:"待开发",attempted:"已尝试联系",connected:"已取得有效联系",needs_details:"需求待补充",evaluable:"需求可评估",paused:"暂缓",not_fit:"不适配",do_not_contact:"停止联系"};
const taskLabels:Record<string,string>={unassigned:"待分配",pending:"待处理",in_progress:"处理中",submitted:"已提交待检查",needs_more:"待补充",reviewed:"已检查"};
const resultOptions=[["unreachable","未接通"],["bounced","邮箱退信"],["message_sent","已留言/已发出待回复"],["contact_found","已找到负责人"],["willing_to_share","愿意提供需求"],["no_current_need","暂时无需求"],["not_fit","不适配"],["do_not_contact","要求停止联系"]] as const;

export function OutreachWorkbench({viewer}:{viewer:Viewer|null}){
  const [data,setData]=useState<OutreachSnapshot|null>(null);const [status,setStatus]=useState<"loading"|"ready"|"error">("loading");const [notice,setNotice]=useState("");const [tab,setTab]=useState<"tasks"|"leads"|"guide">("tasks");
  const load=()=>{setStatus("loading");readOutreach().then(x=>{setData(x);setStatus("ready")}).catch(e=>{setNotice(e instanceof Error?e.message:"加载失败");setStatus("error")})};
  useEffect(load,[]);const leadById=useMemo(()=>new Map((data?.leads||[]).map(x=>[x.id,x])),[data]);
  return <div className="ow"><header className="ow-head"><div><p>OUTREACH / 客户开发</p><h1>{data?.program.title||"客户开发"}</h1><span>{data?.program.status==="draft"?"试验保持草稿；候选与草稿可准备，未授权任务不派发":"真实客户开发任务"}</span></div><button onClick={load}><RefreshCw size={16}/>刷新</button></header>
    <nav className="ow-tabs"><button className={tab==="tasks"?"active":""} onClick={()=>setTab("tasks")}>我的任务<b>{data?.tasks.filter(x=>x.handoff_status!=="reviewed").length||0}</b></button><button className={tab==="leads"?"active":""} onClick={()=>setTab("leads")}>客户</button><button className={tab==="guide"?"active":""} onClick={()=>setTab("guide")}>怎么交付</button></nav>
    {status!=="ready"&&<div className="ow-warning"><AlertTriangle size={18}/><div><b>{status==="loading"?"正在读取真实数据":"加载失败"}</b><p>{notice||"请稍候"}</p></div></div>}
    {data?.viewer.can_manage&&data.stats&&<section className="ow-stats"><Stat icon={<Target/>} label="首批线索" value={data.stats.total} note={`待分配 ${data.stats.unassigned}`}/><Stat icon={<Send/>} label="实际尝试" value={data.stats.attempted} note="只计真实事件"/><Stat icon={<Users/>} label="有效联系" value={data.stats.connected} note="按客户去重"/><Stat icon={<CheckCircle2/>} label="需求可评估" value={data.stats.evaluable} note={`待补充 ${data.stats.needs_details}`}/></section>}
    {tab==="tasks"&&<section className="ow-panel"><div className="ow-panel-head"><h2>现在做什么</h2><span>{data?.tasks.length||0} 条</span></div><div className="ow-cards">{data?.tasks.map(task=><TaskCard key={task.id} task={task} lead={leadById.get(task.lead_id)} viewer={viewer} attachments={data.attachments.filter(x=>x.task_id===task.id)} onChanged={load} onNotice={setNotice}/>)}</div>{data&&!data.tasks.length&&<Empty title="当前没有可见任务" text="未分配客户只对老板和 Codex 可见；业务员只会看到本人任务。"/>}</section>}
    {tab==="leads"&&<section className="ow-panel"><div className="ow-panel-head"><h2>本人客户与来源</h2><span><Search size={15}/>{data?.leads.length||0} 家</span></div><div className="ow-table"><table><thead><tr><th>企业 / 城市</th><th>为什么联系</th><th>进展</th><th>来源与未确认</th></tr></thead><tbody>{data?.leads.map(lead=>{const sources=data.sources.filter(x=>x.lead_id===lead.id);return <tr key={lead.id}><td><b>{lead.company_name}</b><small>{lead.city} · {lead.country}</small><small>{lead.primary_email||lead.primary_phone||"待补联系入口"}</small></td><td>{lead.suggested_entry}<small>{lead.fit_reason}</small></td><td>{progressLabels[lead.progress_status]||lead.progress_status}<small>需求：{lead.demand_status==="unknown"?"未确认":lead.demand_status}；中国供货：{lead.china_supply_status==="unknown"?"未知":lead.china_supply_status}</small></td><td>{sources.map(s=><div key={s.id}><a href={s.source_url} target="_blank" rel="noreferrer">{s.item_ref} · {s.observed_at}</a><small>{s.evidence_limit}</small></div>)}</td></tr>})}</tbody></table></div></section>}
    {tab==="guide"&&<Guide/>}{notice&&<button className="ow-toast" onClick={()=>setNotice("")}>{notice}</button>}</div>;
}
function Stat({icon,label,value,note}:{icon:ReactNode;label:string;value:number;note:string}){return <article>{icon}<span>{label}</span><b>{value}</b><small>{note}</small></article>}
function Empty({title,text}:{title:string;text:string}){return <div className="ow-empty"><h3>{title}</h3><p>{text}</p></div>}

function TaskCard({task,lead,viewer,attachments,onChanged,onNotice}:{task:OutreachTask;lead?:OutreachSnapshot["leads"][number];viewer:Viewer|null;attachments:OutreachSnapshot["attachments"];onChanged:()=>void;onNotice:(x:string)=>void}){
  const mine=viewer?.role==="sales"&&task.owner_person_id===viewer.person_id;const [open,setOpen]=useState(task.handoff_status==="in_progress"||task.handoff_status==="needs_more");const [busy,setBusy]=useState(false);
  async function start(){setBusy(true);try{await startOutreachTask(task.id,task.revision);onNotice("服务器已记录开始处理");onChanged()}catch(e){onNotice(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}}
  return <article className="ow-task"><div><span>{lead?.company_name||"客户"}</span><b>{taskLabels[task.handoff_status]||task.handoff_status}</b></div><h3>{task.title}</h3><p><strong>现在做什么：</strong>{task.action_text}</p><p><strong>找谁：</strong>{task.contact_target}</p><details><summary>查看俄语草稿与中文意思</summary><p className="ow-draft">{task.russian_draft||"草稿待 Codex 准备；可先电话询问负责人。"}</p><p className="ow-translation">{task.chinese_translation}</p></details><p><strong>这次交什么：</strong>{task.delivery_requirements}</p><small>截止/跟进：{task.due_at||"待安排"} · 下一步：{task.next_step}</small>{task.review_note&&<p className="ow-feedback">最新检查：{task.review_note}</p>}{mine&&task.handoff_status==="pending"&&<button disabled={busy} onClick={()=>void start()}>开始处理</button>}{mine&&["in_progress","needs_more"].includes(task.handoff_status)&&<button onClick={()=>setOpen(!open)}>记录联系结果 / 提交反馈</button>}{open&&mine&&<FeedbackForm task={task} attachments={attachments} onChanged={onChanged} onNotice={onNotice}/>}</article>;
}
function FeedbackForm({task,attachments,onChanged,onNotice}:{task:OutreachTask;attachments:OutreachSnapshot["attachments"];onChanged:()=>void;onNotice:(x:string)=>void}){
  const [busy,setBusy]=useState(false);const [idempotencyKey]=useState(()=>crypto.randomUUID());const [form,setForm]=useState({happened_at:new Date().toISOString().slice(0,16),channel:"phone",address_used:"",contact_name:"",contact_role:"",result:"unreachable",customer_quote:"",operator_summary:"",next_action:"",next_date:"",waiting_for:"",verification_level:"operator_statement"});const change=(key:string,value:string)=>setForm({...form,[key]:value});
  async function upload(file?:File){if(!file)return;setBusy(true);try{await uploadOutreachAttachment(task.id,file);onNotice(`附件 ${file.name} 已由服务器校验保存`);onChanged()}catch(e){onNotice(e instanceof Error?e.message:"附件上传失败")}finally{setBusy(false)}}
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{const value={...form,happened_at:new Date(form.happened_at).toISOString(),next_date:form.next_date||null,revision:task.revision,idempotency_key:idempotencyKey};const result=await submitOutreachEvent(task.id,value);onNotice(`服务器已接收：${result.receipt.event_id} · 待 Codex 检查`);onChanged()}catch(err){onNotice(err instanceof Error?err.message:"提交失败")}finally{setBusy(false)}}
  return <form className="ow-feedback-form" onSubmit={e=>void submit(e)}><label>实际发生时间<input type="datetime-local" required value={form.happened_at} onChange={e=>change("happened_at",e.target.value)}/></label><label>渠道<select value={form.channel} onChange={e=>change("channel",e.target.value)}><option value="phone">电话</option><option value="email">邮件</option><option value="chat">聊天</option><option value="form">官网表单</option></select></label><label>实际联系方式<input required value={form.address_used} onChange={e=>change("address_used",e.target.value)}/></label><label>结果<select value={form.result} onChange={e=>change("result",e.target.value)}>{resultOptions.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label>对方姓名<input value={form.contact_name} onChange={e=>change("contact_name",e.target.value)} placeholder="未知可留空"/></label><label>对方职位<input value={form.contact_role} onChange={e=>change("contact_role",e.target.value)} placeholder="未知可留空"/></label><label className="wide">客户原话<textarea value={form.customer_quote} onChange={e=>change("customer_quote",e.target.value)}/></label><label className="wide">书面纪要<textarea required value={form.operator_summary} onChange={e=>change("operator_summary",e.target.value)}/></label><label>下一步动作<input value={form.next_action} onChange={e=>change("next_action",e.target.value)}/></label><label>下一次日期<input type="date" value={form.next_date} onChange={e=>change("next_date",e.target.value)}/></label><label className="wide">等待谁 / 什么<input value={form.waiting_for} onChange={e=>change("waiting_for",e.target.value)}/></label><label>证据口径<select value={form.verification_level} onChange={e=>change("verification_level",e.target.value)}><option value="operator_statement">业务员陈述，未独立核实</option><option value="independent">有独立附件证据</option></select></label><label className="ow-upload">附件<input type="file" disabled={busy} onChange={e=>void upload(e.target.files?.[0])}/><small>已验证 {attachments.filter(x=>x.status==="verified").length} 个</small></label><button type="submit" disabled={busy}><FileUp size={15}/>提交反馈</button></form>;
}
function Guide(){return <section className="ow-panel ow-guide"><h2>业务员交付说明</h2><ol><li>使用自己的工作邮箱登录；没有任务时确认分配，不借用账号。</li><li>打开“待处理”任务，确认现在做什么、找谁和这次交什么，点“开始处理”。</li><li>俄语草稿必须替换为本人姓名；只使用卡片中已批准资料。</li><li>在真实电话、邮件或聊天工具中联系；复制草稿不算已联系。</li><li>回到同一任务，如实记录结果、客户原话和证据；未知信息保持未知。</li><li>点“提交反馈”，看到服务器回执后才算交付。</li><li>查看“已提交待检查”或“待补充”；补交继续使用同一任务。</li></ol><p>退信、未接通、找错联系人或没有需求都照实提交；不得为了改变状态编写结果。</p></section>}
